version: "3.1"
services:
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: "no"
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    depends_on:
      - mongodb
    environment:
      - PORT=3005
      - EXPIRES_IN=1h
      - SECRET=MY_SECRET_KEY
      - DB_URL=mongodb://mongodb:27017/jj
    restart: "no"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: "no"
